package com.ijh165.postalsystem.frontend.dialog;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 * DO NOT override the setTitle() method of this class!!!!!!
 * @author IvanJonathan
 */
public class BuildCommandDialog extends javax.swing.JDialog {

    /**
     * Creates new form BuildCommandDialog
     */
    public BuildCommandDialog(java.awt.Frame parent, boolean modal, boolean isBuildCommandDialog) {
        //basic initialization
        super(parent, modal);
        initComponents();
        //center depending on parent
        super.setLocationRelativeTo(parent);
        //set title depending on isBuildCommandDialog
        setTitle(isBuildCommandDialog?"BUILD Command":"Enter Office Info");
        //initialize variables
        command = null;
        this.isBuildCommandDialog = isBuildCommandDialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        officeNameLabel = new javax.swing.JLabel();
        transitTimeLabel = new javax.swing.JLabel();
        requiredPostageLabel = new javax.swing.JLabel();
        capacityLabel = new javax.swing.JLabel();
        persuasionAmountLabel = new javax.swing.JLabel();
        maxPackageLengthLabel = new javax.swing.JLabel();
        officeNameTextField = new javax.swing.JTextField();
        transitTimeTextField = new javax.swing.JTextField();
        requiredPostageTextField = new javax.swing.JTextField();
        capacityTextField = new javax.swing.JTextField();
        persuasionAmountTextField = new javax.swing.JTextField();
        maxPackageLengthTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        officeNameLabel.setText("Post Office Name:");

        transitTimeLabel.setText("Transit Time:");

        requiredPostageLabel.setText("Required Postage:");

        capacityLabel.setText("Capacity:");

        persuasionAmountLabel.setText("Persuasion Amount:");

        maxPackageLengthLabel.setText("Maximum Package Length:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(officeNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(capacityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(requiredPostageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(transitTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(persuasionAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transitTimeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(requiredPostageTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(capacityTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(persuasionAmountTextField)
                    .addComponent(officeNameTextField)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(730, Short.MAX_VALUE)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(maxPackageLengthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxPackageLengthTextField))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(officeNameTextField)
                    .addComponent(officeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transitTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transitTimeTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requiredPostageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requiredPostageTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacityTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(persuasionAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persuasionAmountTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxPackageLengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxPackageLengthTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        //fetch input
        String officeName = officeNameTextField.getText();
        String transitTime = transitTimeTextField.getText();
        String requiredPostage =  requiredPostageTextField.getText();
        String capacity = capacityTextField.getText();
        String persuasionAmount = persuasionAmountTextField.getText();
        String maxPackageLength = maxPackageLengthTextField.getText();
        //check for empty input
        if (officeName.length()==0 || transitTime.length()==0 || requiredPostage.length()==0 ||
            capacity.length()==0 || persuasionAmount.length()==0 || maxPackageLength.length()==0)
        {
            JOptionPane.showMessageDialog(this, "All fields cannot be empty!",
                                          "Required information missing!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //validate input
        Pattern nonAlphabeticPattern = Pattern.compile("[^a-zA-Z]");
        Pattern nonNumericPattern = Pattern.compile("[^0-9]");
        if ( nonAlphabeticPattern.matcher(officeName).find() ||
             nonNumericPattern.matcher(transitTime).find() ||
             nonNumericPattern.matcher(requiredPostage).find() ||
             nonNumericPattern.matcher(capacity).find() ||
             nonNumericPattern.matcher(persuasionAmount).find() || 
             nonNumericPattern.matcher(maxPackageLength).find() )
        {
            String officeNameString = officeNameLabel.getText().substring(0, officeNameLabel.getText().length()-1);
            String transitTimeString = transitTimeLabel.getText().substring(0, transitTimeLabel.getText().length()-1);
            String requiredPostageString = requiredPostageLabel.getText().substring(0, requiredPostageLabel.getText().length()-1);
            String capacityString = capacityLabel.getText().substring(0, capacityLabel.getText().length()-1);
            String persuationAmountString = persuasionAmountLabel.getText().substring(0, persuasionAmountLabel.getText().length()-1);
            String maxPackageLengthString = maxPackageLengthLabel.getText().substring(0, maxPackageLengthLabel.getText().length()-1);
            
            JOptionPane.showMessageDialog(this,
                                          "All fields must not contain spaces!\n" +
                                          "\"" + officeNameString + "\" " + 
                                          "must be alphabetic!\n" +
                                          "\"" + transitTimeString + "\", " +
                                          "\"" + requiredPostageString + "\", " +
                                          "\"" + capacityString + "\", " +
                                          "\"" + persuationAmountString + "\", and " +
                                          "\"" + maxPackageLengthString + "\" " +
                                          "must be non negative integer!\n",
                                          "Invalid input!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //concatenate into command
        if (isBuildCommandDialog) {
            command = "BUILD " + officeName + " " + transitTime + " " + requiredPostage + " " + capacity + " " + persuasionAmount + " " + maxPackageLength;
        } else {
            command = officeName + " " + transitTime + " " + requiredPostage + " " + capacity + " " + persuasionAmount + " " + maxPackageLength;
        }
        //close dialog
        dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    public void setOfficeNameTextField(String text) {
        officeNameTextField.setText(text);
    }
    
    public void setTransitTimeTextField(String text) {
        transitTimeTextField.setText(text);
    }
    
    public void setRequiredPostageTextField(String text) {
        requiredPostageTextField.setText(text);
    }
    
    public void setCapacityTextField(String text) {
        capacityTextField.setText(text);
    }
    
    public void setPersuasionAmountTextField(String text) {
        persuasionAmountTextField.setText(text);
    }
    
    public void setMaxPackageLengthTextField(String text) {
        maxPackageLengthTextField.setText(text);
    }
    
    public String getCommand() {
        return command;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JTextField capacityTextField;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel maxPackageLengthLabel;
    private javax.swing.JTextField maxPackageLengthTextField;
    private javax.swing.JLabel officeNameLabel;
    private javax.swing.JTextField officeNameTextField;
    private javax.swing.JLabel persuasionAmountLabel;
    private javax.swing.JTextField persuasionAmountTextField;
    private javax.swing.JLabel requiredPostageLabel;
    private javax.swing.JTextField requiredPostageTextField;
    private javax.swing.JLabel transitTimeLabel;
    private javax.swing.JTextField transitTimeTextField;
    // End of variables declaration//GEN-END:variables

    private String command;
    private final boolean isBuildCommandDialog;
}
