package com.ijh165.postalsystem.frontend.dialog;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author IvanJonathan
 */
public class LetterCommandDialog extends javax.swing.JDialog {

    /**
     * Creates new form LetterCommandDialog
     */
    public LetterCommandDialog(java.awt.Frame parent, boolean modal) {
        //basic initialization
        super(parent, modal);
        initComponents();
        //center depending on parent
        super.setLocationRelativeTo(parent);
        //initialize completeCommand
        command = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initOfficeLabel = new javax.swing.JLabel();
        recipientLabel = new javax.swing.JLabel();
        destOfficeLabel = new javax.swing.JLabel();
        returnRecipientLabel = new javax.swing.JLabel();
        initOfficeTextField = new javax.swing.JTextField();
        recipientTextField = new javax.swing.JTextField();
        destOfficeTextField = new javax.swing.JTextField();
        returnRecipientTextField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LETTER Command");

        initOfficeLabel.setText("Initiating Post Office:");

        recipientLabel.setText("Recipient:");

        destOfficeLabel.setText("Destination Post Office:");

        returnRecipientLabel.setText("Return Recipient:");

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(initOfficeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recipientLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destOfficeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnRecipientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(initOfficeTextField)
                    .addComponent(returnRecipientTextField)
                    .addComponent(destOfficeTextField)
                    .addComponent(recipientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(initOfficeTextField)
                    .addComponent(initOfficeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recipientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recipientTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destOfficeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destOfficeTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnRecipientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnRecipientTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        //fetch input
        String initOfficeName = initOfficeTextField.getText();
        String recipient = recipientTextField.getText();
        String destOfficeName = destOfficeTextField.getText();
        String returnRecipient = returnRecipientTextField.getText();
        //check for empty input
        if (initOfficeName.length()==0 || recipient.length() == 0 || 
            destOfficeName.length()==0 || returnRecipient.length()==0)
        {
            JOptionPane.showMessageDialog(this, "All fields cannot be empty!", 
                                          "Required information missing!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //validate input
        final Pattern nonAlphabeticPattern = Pattern.compile("[^a-zA-Z]");
        if ( nonAlphabeticPattern.matcher(initOfficeName).find() || nonAlphabeticPattern.matcher(recipient).find() ||
             nonAlphabeticPattern.matcher(destOfficeName).find() || nonAlphabeticPattern.matcher(returnRecipient).find() )
        {
            JOptionPane.showMessageDialog(this, "All fields must be alphabetic and must not contain spaces!",
                                          "Invalid input!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //concatenate into command
        command = "LETTER " + initOfficeName + " " + recipient + " " + destOfficeName + " " + returnRecipient;
        //close dialog
        dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    public void setInitOfficeTextField(String text) {
        initOfficeTextField.setText(text);
    }
    
    public void setRecipientTextField(String text) {
        recipientTextField.setText(text);
    }
    
    public void setDestOfficeTextField(String text) {
        destOfficeTextField.setText(text);
    }
    
    public void setReturnRecipientTextField(String text) {
        returnRecipientTextField.setText(text);
    }
    
    public String getCommand() {
        return command;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel destOfficeLabel;
    private javax.swing.JTextField destOfficeTextField;
    private javax.swing.JLabel initOfficeLabel;
    private javax.swing.JTextField initOfficeTextField;
    private javax.swing.JLabel recipientLabel;
    private javax.swing.JTextField recipientTextField;
    private javax.swing.JLabel returnRecipientLabel;
    private javax.swing.JTextField returnRecipientTextField;
    // End of variables declaration//GEN-END:variables

    private String command;
}
