package com.ijh165.postalsystem.frontend.dialog;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author IvanJonathan
 */
public class PackageCommandDialog extends javax.swing.JDialog {

    /**
     * Creates new form PackageCommandDialog
     */
    public PackageCommandDialog(java.awt.Frame parent, boolean modal) {
        //basic initialization
        super(parent, modal);
        initComponents();
        //center depending on parent
        super.setLocationRelativeTo(parent);
        //initialize completeCommand
        command = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initOfficeTextField = new javax.swing.JTextField();
        recipientTextField = new javax.swing.JTextField();
        destOfficeTextField = new javax.swing.JTextField();
        moneyTextField = new javax.swing.JTextField();
        lengthTextField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        initOfficeLabel = new javax.swing.JLabel();
        recipientLabel = new javax.swing.JLabel();
        destOfficeLabel = new javax.swing.JLabel();
        moneyLabel = new javax.swing.JLabel();
        lengthLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PACKAGE Command");

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        initOfficeLabel.setText("Initiating Post Office:");

        recipientLabel.setText("Recipient:");

        destOfficeLabel.setText("Destination Post Office:");

        moneyLabel.setText("Money:");

        lengthLabel.setText("Package Length:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(initOfficeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recipientLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destOfficeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moneyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(initOfficeTextField)
                    .addComponent(moneyTextField)
                    .addComponent(recipientTextField)
                    .addComponent(destOfficeTextField)
                    .addComponent(lengthTextField)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(598, Short.MAX_VALUE)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(initOfficeTextField)
                    .addComponent(initOfficeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recipientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recipientTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destOfficeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destOfficeTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneyTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        //fetch input
        String initOfficeName = initOfficeTextField.getText();
        String recipient = recipientTextField.getText();
        String destOfficeName =  destOfficeTextField.getText();
        String money = moneyTextField.getText();
        String length = lengthTextField.getText();
        //check for empty input
        if (initOfficeName.length()==0 || recipient.length()==0 || destOfficeName.length()==0 ||
            money.length()==0 || length.length()==0)
        {
            JOptionPane.showMessageDialog(this, "All fields cannot be empty!", 
                                          "Required information missing!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //validate input
        Pattern nonAlphabeticPattern = Pattern.compile("[^a-zA-Z]");
        Pattern nonNumericPattern = Pattern.compile("[^0-9]");
        if (nonAlphabeticPattern.matcher(initOfficeName).find() || 
            nonAlphabeticPattern.matcher(recipient).find() || 
            nonAlphabeticPattern.matcher(destOfficeName).find() ||
            nonNumericPattern.matcher(money).find() || 
            nonNumericPattern.matcher(length).find())
        {
            String initOfficeString = initOfficeLabel.getText().substring(0, initOfficeLabel.getText().length()-1);
            String recipientString = recipientLabel.getText().substring(0, recipientLabel.getText().length()-1);
            String destOfficeString = destOfficeLabel.getText().substring(0, destOfficeLabel.getText().length()-1);
            String moneyString = moneyLabel.getText().substring(0, moneyLabel.getText().length()-1);
            String lengthString = lengthLabel.getText().substring(0, lengthLabel.getText().length()-1);
            JOptionPane.showMessageDialog(this,
                                          "All fields must not contain spaces!\n" +
                                          "\"" + initOfficeString + "\", " +
                                          "\"" + recipientString + "\" and " +
                                          "\"" + destOfficeString + "\" " +
                                          "must be alphabetic!\n" +
                                          "\"" + moneyString + "\" and " +
                                          "\"" + lengthString + "\" " +
                                          "must be non negative integer!\n",
                                          "Invalid input!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //concatenate into command
        command = "PACKAGE " + initOfficeName + " " + recipient + " " + destOfficeName + " " + money + " " + length;
        //close dialog
        dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    public void setInitOfficeTextField(String text) {
        initOfficeTextField.setText(text);
    }
    
    public void setRecipientTextField(String text) {
        recipientTextField.setText(text);
    }
    
    public void setDestOfficeTextField(String text) {
        destOfficeTextField.setText(text);
    }
    
    public void setMoneyTextField(String text) {
        moneyTextField.setText(text);
    }
    
    public void setLengthTextField(String text) {
        lengthTextField.setText(text);
    }
    
    public String getCommand() {
        return command;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel destOfficeLabel;
    private javax.swing.JTextField destOfficeTextField;
    private javax.swing.JLabel initOfficeLabel;
    private javax.swing.JTextField initOfficeTextField;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JTextField lengthTextField;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JTextField moneyTextField;
    private javax.swing.JLabel recipientLabel;
    private javax.swing.JTextField recipientTextField;
    // End of variables declaration//GEN-END:variables

    private String command;
}
